[platformio]
default_envs = esp8266
src_dir = .
include_dir = .

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.5

[env:esp8266]
platform = espressif8266
board = nodemcuv2
board_build.filesystem = littlefs

[env:esp32]
platform = espressif32
board = esp32dev
board_build.filesystem = littlefs
