[platformio]
default_envs = esp8266

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.5

[env:esp8266]
platform = espressif8266
board = nodemcuv2
board_build.filesystem = littlefs
; OTA upload from VS Code / PlatformIO (set your device IP and optional auth)
upload_protocol = espota
upload_port = 172.16.0.102
;upload_flags = --auth=your_ota_password

[env:esp32]
platform = espressif32
board = esp32dev
board_build.filesystem = littlefs
; OTA upload from VS Code / PlatformIO (set your device IP and optional auth)
;upload_protocol = espota
;upload_port = 172.16.0.98
;upload_flags = --auth=your_ota_password
